# Generated by Django 6.0.7 on 2026-07-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=200)),
                ("award_amount", models.IntegerField()),
                ("education_level", models.CharField(max_length=100)),
                ("discipline", models.CharField(max_length=100)),
                ("prefecture", models.CharField(max_length=100)),
                ("deadline", models.CharField(max_length=50)),
                ("requirements", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("education", models.CharField(blank=True, default="", max_length=100)),
                (
                    "discipline",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "prefecture",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScholarshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scholarship_name", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=200)),
                ("award_amount", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarship_requests",
                        to="scholarships.user",
                    ),
                ),
            ],
        ),
    ]
