# Generated by Django 6.0.7 on 2026-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
