services:
  - type: web
    name: scholarship-finder
    runtime: python
    plan: free
    region: oregon
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn config.wsgi --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: scholarship-finder-db
          property: connectionString

databases:
  - name: scholarship-finder-db
    plan: free
    region: oregon
